### PR TITLE
Implement export command

### PR DESCRIPTION
**Pull request by prgJ**
1. PR related to #118 
2. implements `export` command
3. To run `export`, build.gradle needs to be updated to include 'javafx-swing' dependencies 
4. PR not including test cases atm
5. Checkstyle violations fixed

### CODE REVIEW

**Review by simjunheng — COMMENTED** [review]
LGTM. Just a few questions, where will the newly generated image file be stored at? Also, will the image name be randomised?

**Comment by prgJ** [comment]
The file image is stored in a directory of the users choosing in their local drive! Initially I was considering randomizing the names, but when `Filechooser` prompts users to choose the directory, they're given the option to change the name as well so I scrapped the idea and just implemented a default value. 

imo its probably more useful for coaches to save and categorize their strategies in sections and with names as they deem fit instead of just dumping all of it in one spot? but if you think the randomized thing works better can lmk!

**Comment by simjunheng** [comment]
> @simjunheng The file image is stored in a directory of the users choosing in their local drive! Initially I was considering randomizing the names, but when `Filechooser` prompts users to choose the directory, they're given the option to change the name as well so I scrapped the idea and just implemented a default value.
> 
> imo its probably more useful for coaches to save and categorize their strategies in sections and with names as they deem fit instead of just dumping all of it in one spot? but if you think the randomized thing works better can lmk!

Sounds good. It would be great if this could be implemented for load-court as well. Perhaps we can explore it for v1.4? @AAlghrairy

**Comment by AAlghrairy** [comment]
> > @simjunheng The file image is stored in a directory of the users choosing in their local drive! Initially I was considering randomizing the names, but when `Filechooser` prompts users to choose the directory, they're given the option to change the name as well so I scrapped the idea and just implemented a default value.
> > imo its probably more useful for coaches to save and categorize their strategies in sections and with names as they deem fit instead of just dumping all of it in one spot? but if you think the randomized thing works better can lmk!
> 
> Sounds good. It would be great if this could be implemented for load-court as well. Perhaps we can explore it for v1.4? @AAlghrairy

For load-court, I think it's safer to load images from a pre-defined directory. Also, we aren't allowed to make any changes to the functionality for v1.4, so I don't suppose we can explore it then.

**Pull request merged**
