### PR TITLE
Individual documentation update for v1.3

### PR DESCRIPTION
**Pull request by AAlghrairy**
1. Related to #70 and #71 
2. Adds respective function definitions in UserGuide.md
3. Adds additional user stories and use cases to DeveloperGuide.md
4. Modifies Model component of Developer Guide (replaced Class Diagram) and removed `BetterModelClassDiagram` as it is not used.

### CODE REVIEW

**Comment by simjunheng** [comment]
LGTM except for the model class diagram that is missing the classes for task

**Comment by AAlghrairy** [comment]
> LGTM except for the model class diagram that is missing the classes for task

Thanks for reminding me! I've included the references to task now.

**Review by Rye-Catcher — APPROVED** [review]
LGTM,  I think can merge now

**Comment by juayhee** [comment]
LGTM, I think it's fine to merge

**Pull request merged**
